/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MyTicToc.java
 *
 * Created on Jan 3, 2012, 7:34:17 AM
 */
package tictactoe;

import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Nasir
 */
public class MyTicToc extends javax.swing.JFrame {

    public int take = 1;
    public int turn = 0;
    public int reminder1 = 0;
    public int reminder2 = 0;
    public int reminder3 = 0;
    public int reminder4 = 0;
    public int reminder5 = 0;
    public int reminder6 = 0;
    public int reminder7 = 0;
    public int reminder8 = 0;
    public int reminder9 = 0;
    public int x = 0;
    public int o = 0;
    public int win = 0;
    public int CPU = 1;
    public int CPUHard = 1;
    public int Death_Match = 1;
    public int user = 1;
    public Random rand;
    public Random randDeath;
    public int randomValue;
    public int randomDeathValue;

    /** Creates new form MyTicToc */
    public MyTicToc() {
        super.setTitle("n.TicTocToe");
        setLocationRelativeTo(null);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        playAgain = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pointX = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pointO = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        vs = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setBackground(new java.awt.Color(0, 0, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Score");

        Exit.setBackground(new java.awt.Color(204, 0, 0));
        Exit.setForeground(new java.awt.Color(51, 0, 204));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        playAgain.setBackground(new java.awt.Color(0, 153, 51));
        playAgain.setForeground(new java.awt.Color(51, 0, 204));
        playAgain.setText("Play Again");
        playAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("X =");

        pointX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pointX.setForeground(new java.awt.Color(255, 0, 0));
        pointX.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 23)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("O =");

        pointO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        pointO.setForeground(new java.awt.Color(0, 153, 51));
        pointO.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pointO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pointX, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointX, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointO)
                    .addComponent(jLabel2)))
        );

        jButton8.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        vs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vs.setText("vs CPU(Easy)");

        jMenu1.setText("Game");

        jMenuItem3.setText("Play Again");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Exit");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Play");

        jMenuItem1.setText("Player Vs Player");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Player Vs CPU Easy");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem6.setText("Player Vs CPU Hard");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Death Match");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");

        jMenuItem8.setText("Credits");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(vs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(playAgain))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(vs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playAgain, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder7 == 0) {
            setjButtonText(jButton7);
            reminder7 = 1;
        } else if (reminder7 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder8 == 0) {
            setjButtonText(jButton8);
            reminder8 = 1;
        } else if (reminder8 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder3 == 0) {
            setjButtonText(jButton3);
            reminder3 = 1;
        } else if (reminder3 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder4 == 0) {
            setjButtonText(jButton4);
            reminder4 = 1;
        } else if (reminder4 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder5 == 0) {
            setjButtonText(jButton5);
            reminder5 = 1;
        } else if (reminder5 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder6 == 0) {
            setjButtonText(jButton6);
            reminder6 = 1;
        } else if (reminder6 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder9 == 0) {
            setjButtonText(jButton9);
            reminder9 = 1;
        } else if (reminder9 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder1 == 0) {
            setjButtonText(jButton1);
            reminder1 = 1;
        } else if (reminder1 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        if (reminder2 == 0) {
            setjButtonText(jButton2);
            reminder2 = 1;
        } else if (reminder2 == 1) {
            afterWin();
        }
}//GEN-LAST:event_jButton2ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        System.exit(1);
}//GEN-LAST:event_ExitActionPerformed

    private void playAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com

        win = 0;

        if (turn == 1 && CPU == 0 && CPUHard == 0 && Death_Match == 0) {
            turn = 0;
            take = 2;
        } else if (turn == 2 && CPU == 0 && CPUHard == 0 && Death_Match == 0) {
            turn = 0;
            take = 1;
        }

        reminder1 = 0;
        reminder2 = 0;
        reminder3 = 0;
        reminder4 = 0;
        reminder5 = 0;
        reminder6 = 0;
        reminder7 = 0;
        reminder8 = 0;
        reminder9 = 0;
        jButton1.setText("");
        jButton1.setBackground(null);
        jButton2.setText("");
        jButton2.setBackground(null);
        jButton3.setText("");
        jButton3.setBackground(null);
        jButton4.setText("");
        jButton4.setBackground(null);
        jButton5.setText("");
        jButton5.setBackground(null);
        jButton6.setText("");
        jButton6.setBackground(null);
        jButton7.setText("");
        jButton7.setBackground(null);
        jButton8.setText("");
        jButton8.setBackground(null);
        jButton9.setText("");
        jButton9.setBackground(null);
        if (turn == 2 && CPU == 1) {
            take = 2;
            turn = 0;
            vsCPU();
            turn = 1;
        } else if (turn == 1 && CPU == 1) {
            take = 1;
            turn = 0;
        } else if (turn == 2 && CPUHard == 1) {
            take = 2;
            turn = 0;
            vsCPUHard();
            turn = 1;
        } else if (turn == 1 && CPUHard == 1) {
            take = 1;
            turn = 0;
        } else if (turn == 2 && Death_Match == 1) {
            take = 2;
            turn = 0;
            vsDeathMatch();
            turn = 1;
        } else if (turn == 1 && Death_Match == 1) {
            take = 1;
            turn = 0;
        }

}//GEN-LAST:event_playAgainActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        CPU = 0;
        CPUHard = 0;
        Death_Match = 0;
        vs.setText("PLAYER");
        playAgainActionPerformed(evt);
        x = 0;
        pointX.setText("" + x);
        o = 0;
        pointO.setText("" + o);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        CPU = 1;
        CPUHard = 0;
        Death_Match = 0;
        vs.setText("vs CPU(Easy)");
        playAgainActionPerformed(evt);
        x = 0;
        pointX.setText("" + x);
        o = 0;
        pointO.setText("" + o);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        playAgainActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        ExitActionPerformed(evt);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        CPUHard = 1;
        CPU = 0;
        Death_Match = 0;
        vs.setText("vs CPU(Hard)");
        playAgainActionPerformed(evt);
        x = 0;
        pointX.setText("" + x);
        o = 0;
        pointO.setText("" + o);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        Death_Match = 1;
        CPU = 0;
        CPUHard = 0;
        vs.setText("Death Match");
        playAgainActionPerformed(evt);
        x = 0;
        pointX.setText("" + x);
        o = 0;
        pointO.setText("" + o);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here: Md. Nasir Uddin Bhuiyan Email: nubnasir@gmail.com
        HelpA hp = new HelpA();
        hp.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void setjButtonText(JButton jButton) {
        if (take == 1) {
            if (win == 0) {
                jButton.setText("X");
                jButton.setBackground(Color.red);
                setWinner();
                if (win == 0) {
                    take = 2;
                }
                if (CPU == 1 && win == 0) {
                    vsCPU();
                    take = 1;
                } else if (CPUHard == 1 && win == 0) {
                    vsCPUHard();
                    take = 1;
                } else if (Death_Match == 1 && win == 0) {
                    vsDeathMatch();
                    take = 1;
                }
                if (turn == 0) {
                    turn = 1;
                }
            } else {
                afterWin();
            }
        } else if (take == 2) {
            if (win == 0) {
                jButton.setText("O");
                jButton.setBackground(Color.GREEN);
                setWinner();
                take = 1;
                if (turn == 0) {
                    turn = 2;
                }
            } else {
                afterWin();
            }
        }
    }

    private void setWinner() {
        if ("X".equals(jButton1.getText())) {
            if (jButton1.getText().equals(jButton2.getText()) && jButton1.getText().equals(jButton3.getText())) {

                setWinnerColor(jButton1, jButton2, jButton3);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
            if (jButton1.getText().equals(jButton4.getText()) && jButton1.getText().equals(jButton7.getText())) {

                setWinnerColor(jButton4, jButton1, jButton7);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
            if (jButton1.getText().equals(jButton5.getText()) && jButton1.getText().equals(jButton9.getText())) {

                setWinnerColor(jButton1, jButton5, jButton9);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
        }
        if ("O".equals(jButton1.getText())) {
            if (jButton1.getText().equals(jButton2.getText()) && jButton1.getText().equals(jButton3.getText())) {

                setWinnerColor(jButton1, jButton2, jButton3);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
            if (jButton1.getText().equals(jButton4.getText()) && jButton1.getText().equals(jButton7.getText())) {

                setWinnerColor(jButton1, jButton4, jButton7);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
            if (jButton1.getText().equals(jButton5.getText()) && jButton1.getText().equals(jButton9.getText())) {

                setWinnerColor(jButton1, jButton5, jButton9);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
        }
        if ("X".equals(jButton5.getText())) {
            if (jButton5.getText().equals(jButton4.getText()) && jButton5.getText().equals(jButton6.getText())) {

                setWinnerColor(jButton4, jButton5, jButton6);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
            if (jButton5.getText().equals(jButton2.getText()) && jButton5.getText().equals(jButton8.getText())) {

                setWinnerColor(jButton2, jButton5, jButton8);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
        }
        if ("O".equals(jButton5.getText())) {
            if (jButton5.getText().equals(jButton4.getText()) && jButton5.getText().equals(jButton6.getText())) {

                setWinnerColor(jButton4, jButton5, jButton6);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
            if (jButton5.getText().equals(jButton2.getText()) && jButton5.getText().equals(jButton8.getText())) {

                setWinnerColor(jButton2, jButton5, jButton8);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
        }
        if ("X".equals(jButton9.getText())) {
            if (jButton9.getText().equals(jButton8.getText()) && jButton9.getText().equals(jButton7.getText())) {

                setWinnerColor(jButton7, jButton8, jButton9);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
            if (jButton9.getText().equals(jButton6.getText()) && jButton9.getText().equals(jButton3.getText())) {

                setWinnerColor(jButton3, jButton6, jButton9);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
        }
        if ("O".equals(jButton9.getText())) {
            if (jButton9.getText().equals(jButton8.getText()) && jButton9.getText().equals(jButton7.getText())) {

                setWinnerColor(jButton7, jButton8, jButton9);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
            if (jButton9.getText().equals(jButton6.getText()) && jButton9.getText().equals(jButton3.getText())) {

                setWinnerColor(jButton3, jButton6, jButton9);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
        }
        if ("X".equals(jButton3.getText())) {
            if (jButton3.getText().equals(jButton5.getText()) && jButton3.getText().equals(jButton7.getText())) {

                setWinnerColor(jButton3, jButton5, jButton7);
                x++;
                pointX.setText("" + x);
                win = 1;
            }
        }
        if ("O".equals(jButton3.getText())) {
            if (jButton3.getText().equals(jButton5.getText()) && jButton3.getText().equals(jButton7.getText())) {

                setWinnerColor(jButton3, jButton5, jButton7);
                o++;
                pointO.setText("" + o);
                win = 1;
            }
        }

    }

    public void vsCPU() {
        while (true) {
            rand = new Random();
            randomValue = 1 + rand.nextInt(9);
            if (randomValue == 1 && "".equals(jButton1.getText())) {
                jButton1ActionPerformed(null);
                break;
            } else if (randomValue == 2 && "".equals(jButton2.getText())) {
                jButton2ActionPerformed(null);
                break;
            } else if (randomValue == 3 && "".equals(jButton3.getText())) {
                jButton3ActionPerformed(null);
                break;
            } else if (randomValue == 4 && "".equals(jButton4.getText())) {
                jButton4ActionPerformed(null);
                break;
            } else if (randomValue == 5 && "".equals(jButton5.getText())) {
                jButton5ActionPerformed(null);
                break;
            } else if (randomValue == 6 && "".equals(jButton6.getText())) {
                jButton6ActionPerformed(null);
                break;
            } else if (randomValue == 7 && "".equals(jButton7.getText())) {
                jButton7ActionPerformed(null);
                break;
            } else if (randomValue == 8 && "".equals(jButton8.getText())) {
                jButton8ActionPerformed(null);
                break;
            } else if (randomValue == 9 && "".equals(jButton9.getText())) {
                jButton9ActionPerformed(null);
                break;
            } else if (!"".equals(jButton1.getText()) && !"".equals(jButton2.getText()) && !"".equals(jButton3.getText()) && !"".equals(jButton4.getText()) && !"".equals(jButton5.getText()) && !"".equals(jButton6.getText()) && !"".equals(jButton7.getText()) && !"".equals(jButton8.getText()) && !"".equals(jButton9.getText())) {
                break;
            }
        }
    }

    public void vsCPUHard() {
        while (true) {
            rand = new Random();
            randomValue = 1 + rand.nextInt(9);
            if ("".equals(jButton1.getText()) && (("O".equals(jButton2.getText()) && "O".equals(jButton3.getText())) || ("O".equals(jButton4.getText()) && "O".equals(jButton7.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton9.getText())))) {
                jButton1ActionPerformed(null);
                break;
            } else if ("".equals(jButton2.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton3.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton8.getText())))) {
                jButton2ActionPerformed(null);
                break;
            } else if ("".equals(jButton3.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton2.getText())) || ("O".equals(jButton6.getText()) && "O".equals(jButton9.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton7.getText())))) {
                jButton3ActionPerformed(null);
                break;
            } else if ("".equals(jButton4.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton7.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton6.getText())))) {
                jButton4ActionPerformed(null);
                break;
            } else if ("".equals(jButton5.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton9.getText())) || ("O".equals(jButton3.getText()) && "O".equals(jButton7.getText())) || ("O".equals(jButton2.getText()) && "O".equals(jButton8.getText())) || ("O".equals(jButton4.getText()) && "O".equals(jButton6.getText())))) {
                jButton5ActionPerformed(null);
                break;
            } else if ("".equals(jButton6.getText()) && (("O".equals(jButton3.getText()) && "O".equals(jButton9.getText())) || ("O".equals(jButton4.getText()) && "O".equals(jButton5.getText())))) {
                jButton6ActionPerformed(null);
                break;
            } else if ("".equals(jButton7.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton4.getText())) || ("O".equals(jButton3.getText()) && "O".equals(jButton5.getText())) || ("O".equals(jButton8.getText()) && "O".equals(jButton9.getText())))) {
                jButton7ActionPerformed(null);
                break;
            } else if ("".equals(jButton8.getText()) && (("O".equals(jButton2.getText()) && "O".equals(jButton5.getText())) || ("O".equals(jButton7.getText()) && "O".equals(jButton9.getText())))) {
                jButton8ActionPerformed(null);
                break;
            } else if ("".equals(jButton9.getText()) && (("O".equals(jButton3.getText()) && "O".equals(jButton6.getText())) || ("O".equals(jButton7.getText()) && "O".equals(jButton8.getText())) || ("O".equals(jButton1.getText()) && "O".equals(jButton5.getText())))) {
                jButton9ActionPerformed(null);
                break;
            } else if ("".equals(jButton1.getText()) && (("X".equals(jButton2.getText()) && "X".equals(jButton3.getText())) || ("X".equals(jButton4.getText()) && "X".equals(jButton7.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton9.getText())))) {
                jButton1ActionPerformed(null);
                break;
            } else if ("".equals(jButton2.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton3.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton8.getText())))) {
                jButton2ActionPerformed(null);
                break;
            } else if ("".equals(jButton3.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton2.getText())) || ("X".equals(jButton6.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton7.getText())))) {
                jButton3ActionPerformed(null);
                break;
            } else if ("".equals(jButton4.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton7.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton6.getText())))) {
                jButton4ActionPerformed(null);
                break;
            } else if ("".equals(jButton5.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton3.getText()) && "X".equals(jButton7.getText())) || ("X".equals(jButton2.getText()) && "X".equals(jButton8.getText())) || ("X".equals(jButton4.getText()) && "X".equals(jButton6.getText())))) {
                jButton5ActionPerformed(null);
                break;
            } else if ("".equals(jButton6.getText()) && (("X".equals(jButton3.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton4.getText()) && "X".equals(jButton5.getText())))) {
                jButton6ActionPerformed(null);
                break;
            } else if ("".equals(jButton7.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton4.getText())) || ("X".equals(jButton3.getText()) && "X".equals(jButton5.getText())) || ("X".equals(jButton8.getText()) && "X".equals(jButton9.getText())))) {
                jButton7ActionPerformed(null);
                break;
            } else if ("".equals(jButton8.getText()) && (("X".equals(jButton2.getText()) && "X".equals(jButton5.getText())) || ("X".equals(jButton7.getText()) && "X".equals(jButton9.getText())))) {
                jButton8ActionPerformed(null);
                break;
            } else if ("".equals(jButton9.getText()) && (("X".equals(jButton3.getText()) && "X".equals(jButton6.getText())) || ("X".equals(jButton7.getText()) && "X".equals(jButton8.getText())) || ("X".equals(jButton1.getText()) && "X".equals(jButton5.getText())))) {
                jButton9ActionPerformed(null);
                break;
            } else if (randomValue == 1 && "".equals(jButton1.getText())) {
                jButton1ActionPerformed(null);
                break;
            } else if (randomValue == 2 && "".equals(jButton2.getText())) {
                jButton2ActionPerformed(null);
                break;
            } else if (randomValue == 3 && "".equals(jButton3.getText())) {
                jButton3ActionPerformed(null);
                break;
            } else if (randomValue == 4 && "".equals(jButton4.getText())) {
                jButton4ActionPerformed(null);
                break;
            } else if (randomValue == 5 && "".equals(jButton5.getText())) {
                jButton5ActionPerformed(null);
                break;
            } else if (randomValue == 6 && "".equals(jButton6.getText())) {
                jButton6ActionPerformed(null);
                break;
            } else if (randomValue == 7 && "".equals(jButton7.getText())) {
                jButton7ActionPerformed(null);
                break;
            } else if (randomValue == 8 && "".equals(jButton8.getText())) {
                jButton8ActionPerformed(null);
                break;
            } else if (randomValue == 9 && "".equals(jButton9.getText())) {
                jButton9ActionPerformed(null);
                break;
            } else if (!"".equals(jButton1.getText()) && !"".equals(jButton2.getText()) && !"".equals(jButton3.getText()) && !"".equals(jButton4.getText()) && !"".equals(jButton5.getText()) && !"".equals(jButton6.getText()) && !"".equals(jButton7.getText()) && !"".equals(jButton8.getText()) && !"".equals(jButton9.getText())) {
                break;
            }
        }
    }

    public void vsDeathMatch() {
        while (true) {
            rand = new Random();
            randDeath = new Random();
            randomValue = 1 + rand.nextInt(9);
            randomDeathValue = 1 + randDeath.nextInt(4);
            if ("".equals(jButton1.getText()) && (("O".equals(jButton2.getText()) && "O".equals(jButton3.getText())) || ("O".equals(jButton4.getText()) && "O".equals(jButton7.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton9.getText())))) {
                jButton1ActionPerformed(null);
                break;
            } else if ("".equals(jButton2.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton3.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton8.getText())))) {
                jButton2ActionPerformed(null);
                break;
            } else if ("".equals(jButton3.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton2.getText())) || ("O".equals(jButton6.getText()) && "O".equals(jButton9.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton7.getText())))) {
                jButton3ActionPerformed(null);
                break;
            } else if ("".equals(jButton4.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton7.getText())) || ("O".equals(jButton5.getText()) && "O".equals(jButton6.getText())))) {
                jButton4ActionPerformed(null);
                break;
            } else if ("".equals(jButton5.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton9.getText())) || ("O".equals(jButton3.getText()) && "O".equals(jButton7.getText())) || ("O".equals(jButton2.getText()) && "O".equals(jButton8.getText())) || ("O".equals(jButton4.getText()) && "O".equals(jButton6.getText())))) {
                jButton5ActionPerformed(null);
                break;
            } else if ("".equals(jButton6.getText()) && (("O".equals(jButton3.getText()) && "O".equals(jButton9.getText())) || ("O".equals(jButton4.getText()) && "O".equals(jButton5.getText())))) {
                jButton6ActionPerformed(null);
                break;
            } else if ("".equals(jButton7.getText()) && (("O".equals(jButton1.getText()) && "O".equals(jButton4.getText())) || ("O".equals(jButton3.getText()) && "O".equals(jButton5.getText())) || ("O".equals(jButton8.getText()) && "O".equals(jButton9.getText())))) {
                jButton7ActionPerformed(null);
                break;
            } else if ("".equals(jButton8.getText()) && (("O".equals(jButton2.getText()) && "O".equals(jButton5.getText())) || ("O".equals(jButton7.getText()) && "O".equals(jButton9.getText())))) {
                jButton8ActionPerformed(null);
                break;
            } else if ("".equals(jButton9.getText()) && (("O".equals(jButton3.getText()) && "O".equals(jButton6.getText())) || ("O".equals(jButton7.getText()) && "O".equals(jButton8.getText())) || ("O".equals(jButton1.getText()) && "O".equals(jButton5.getText())))) {
                jButton9ActionPerformed(null);
                break;
            } else if ("".equals(jButton1.getText()) && (("X".equals(jButton2.getText()) && "X".equals(jButton3.getText())) || ("X".equals(jButton4.getText()) && "X".equals(jButton7.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton9.getText())))) {
                jButton1ActionPerformed(null);
                break;
            } else if ("".equals(jButton2.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton3.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton8.getText())))) {
                jButton2ActionPerformed(null);
                break;
            } else if ("".equals(jButton3.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton2.getText())) || ("X".equals(jButton6.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton7.getText())))) {
                jButton3ActionPerformed(null);
                break;
            } else if ("".equals(jButton4.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton7.getText())) || ("X".equals(jButton5.getText()) && "X".equals(jButton6.getText())))) {
                jButton4ActionPerformed(null);
                break;
            } else if ("".equals(jButton5.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton3.getText()) && "X".equals(jButton7.getText())) || ("X".equals(jButton2.getText()) && "X".equals(jButton8.getText())) || ("X".equals(jButton4.getText()) && "X".equals(jButton6.getText())))) {
                jButton5ActionPerformed(null);
                break;
            } else if ("".equals(jButton6.getText()) && (("X".equals(jButton3.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton4.getText()) && "X".equals(jButton5.getText())))) {
                jButton6ActionPerformed(null);
                break;
            } else if ("".equals(jButton7.getText()) && (("X".equals(jButton1.getText()) && "X".equals(jButton4.getText())) || ("X".equals(jButton3.getText()) && "X".equals(jButton5.getText())) || ("X".equals(jButton8.getText()) && "X".equals(jButton9.getText())))) {
                jButton7ActionPerformed(null);
                break;
            } else if ("".equals(jButton8.getText()) && (("X".equals(jButton2.getText()) && "X".equals(jButton5.getText())) || ("X".equals(jButton7.getText()) && "X".equals(jButton9.getText())))) {
                jButton8ActionPerformed(null);
                break;
            } else if ("".equals(jButton9.getText()) && (("X".equals(jButton3.getText()) && "X".equals(jButton6.getText())) || ("X".equals(jButton7.getText()) && "X".equals(jButton8.getText())) || ("X".equals(jButton1.getText()) && "X".equals(jButton5.getText())))) {
                jButton9ActionPerformed(null);
                break;
            } else if ("".equals(jButton5.getText())) {
                jButton5ActionPerformed(null);
                break;
            } else if (("X".equals(jButton1.getText()) && "X".equals(jButton9.getText())) || ("X".equals(jButton3.getText()) && "X".equals(jButton7.getText()))) {
                if ("".equals(jButton2.getText())) {
                    jButton2ActionPerformed(null);
                } else if ("".equals(jButton4.getText())) {
                    jButton4ActionPerformed(null);
                } else if ("".equals(jButton6.getText())) {
                    jButton6ActionPerformed(null);
                } else if ("".equals(jButton8.getText())) {
                    jButton8ActionPerformed(null);
                }
                break;
            } else if (randomDeathValue == 1 && "".equals(jButton1.getText())) {
                jButton1ActionPerformed(null);
                break;
            } else if (randomDeathValue == 2 && "".equals(jButton3.getText())) {
                jButton3ActionPerformed(null);
                break;
            } else if (randomDeathValue == 3 && "".equals(jButton7.getText())) {
                jButton7ActionPerformed(null);
                break;
            } else if (randomDeathValue == 4 && "".equals(jButton9.getText())) {
                jButton9ActionPerformed(null);
                break;
            } else if ("".equals(jButton1.getText())) {
                jButton1ActionPerformed(null);
                break;
            } else if ("".equals(jButton3.getText())) {
                jButton3ActionPerformed(null);
                break;
            } else if ("".equals(jButton7.getText())) {
                jButton7ActionPerformed(null);
                break;
            } else if ("".equals(jButton9.getText())) {
                jButton9ActionPerformed(null);
                break;
            } else if (randomValue == 5 && "".equals(jButton5.getText())) {
                jButton5ActionPerformed(null);
                break;
            } else if (randomValue == 6 && "".equals(jButton6.getText())) {
                jButton6ActionPerformed(null);
                break;
            } else if (randomValue == 2 && "".equals(jButton2.getText())) {
                jButton2ActionPerformed(null);
                break;
            } else if (randomValue == 8 && "".equals(jButton8.getText())) {
                jButton8ActionPerformed(null);
                break;
            } else if (randomValue == 4 && "".equals(jButton4.getText())) {
                jButton4ActionPerformed(null);
                break;
            } else if (!"".equals(jButton1.getText()) && !"".equals(jButton2.getText()) && !"".equals(jButton3.getText()) && !"".equals(jButton4.getText()) && !"".equals(jButton5.getText()) && !"".equals(jButton6.getText()) && !"".equals(jButton7.getText()) && !"".equals(jButton8.getText()) && !"".equals(jButton9.getText())) {
                break;
            }
        }
    }

    public void setWinnerColor(JButton j1, JButton j2, JButton j3) {

        j1.setBackground(Color.MAGENTA);
        j2.setBackground(Color.MAGENTA);
        j3.setBackground(Color.MAGENTA);
        if ("X".equals(j1.getText())) {
            JOptionPane.showMessageDialog(null, "X wins!");
        } else if ("O".equals(j1.getText())) {
            JOptionPane.showMessageDialog(null, "O wins!");
        }
    }

    public void afterWin() {

        if (win == 1) {
            JOptionPane.showMessageDialog(null, "This match is already finished.");
        } else {
            JOptionPane.showMessageDialog(null, "This button is already pressed.");
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton playAgain;
    private javax.swing.JLabel pointO;
    private javax.swing.JLabel pointX;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables
}
